### ISSUE TITLE
Simplify CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [3dsam/prj-rev-bwfs-dasmoto#6]
It is good to try and simplify the CSS code to make the code cleaner and to remove repetitive code. There are a few shared properties for the selectors, which you might simplify like so

```css
h1, h2, span {
  font-family: Helvetica;
  font-weight: bold;
}
h1 {
  font-size: 100px;
  color: khaki;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align: center;
}
h2 {
  font-size: 32px;
  color: White;
}
#brush {
  background-color: mediumspringgreen;
}
#frames {
  background-color: lightcoral;
}
#paint{
  background-color: skyblue;
}
#Hacksaw_Brushes, #art_frames, #clean_finnish_paint {
  color: blue;
}
```
